} catch (err) {
  const error = err as Error;
